remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
- jekyll-remote-theme 
- jekyll-include-cache
colors:
    gradient_left: "#073058"
    gradient_right: "#159957"
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: false
