remote_theme: pages-themes/cayman@v0.2.0
title: KNOWAGE Gallery Templates
description: Willing to take your data visualization to a higher level?
plugins:
- jekyll-remote-theme 
colors:
    gradient_left: "#073058"
    gradient_right: "#159957"